# Generated by Django 5.0.6 on 2024-05-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_smart', '0003_alter_temperaturadata_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contadordata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='luminosidadedata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='umidadedata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
